"""add sms_message table

Revision ID: 0b6b19f7eaf3
Revises: c3955592df46
Create Date: 2026-09-26 14:51:27.395954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6b19f7eaf3'
down_revision: Union[str, Sequence[str], None] = 'c3955592df46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_band', sa.String(), nullable=True),
    sa.Column('extracted_iocs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_messages_id'), 'sms_messages', ['id'], unique=False)
    op.create_index(op.f('ix_sms_messages_sender'), 'sms_messages', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_messages_sender'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    # ### end Alembic commands ###
